function OnPackageStart()
    local pakname = "luminousarrowtwo"
	local res = LoadPak(pakname, "/luminousarrowtwo/", "../../../OnsetModding/Plugins/luminousarrowtwo/Content")
	res = ReplaceObjectModelMesh(45, "/luminousarrowtwo/flechelumineusedeux")
	local pakname = "taxisign"
	local res = LoadPak(pakname, "/taxisign/", "../../../OnsetModding/Plugins/taxisign/Content")
	res = ReplaceObjectModelMesh(47, "/taxisign/Panneau_Sol")
	local pakname = "tbillboardad"
	local res = LoadPak(pakname, "/tbillboardad/", "../../../OnsetModding/Plugins/tbillboardad/Content")
	res = ReplaceObjectModelMesh(48, "/tbillboardad/Panneau_Publicitaire")
	local pakname = "troadsign"
	local res = LoadPak(pakname, "/troadsign/", "../../../OnsetModding/Plugins/troadsign/Content")
	res = ReplaceObjectModelMesh(49, "/troadsign/Panneau_Routier")
	local pakname = "twallsign"
	local res = LoadPak(pakname, "/twallsign/", "../../../OnsetModding/Plugins/twallsign/Content")
	res = ReplaceObjectModelMesh(50, "/twallsign/Panneau_Mural")
	local pakname = "plargefrontsign"
	local res = LoadPak(pakname, "/plargefrontsign/", "../../../OnsetModding/Plugins/plargefrontsign/Content")
	res = ReplaceObjectModelMesh(57, "/plargefrontsign/plargefrontsign")
	local pakname = "pmediumfrontsign"
	local res = LoadPak(pakname, "/pmediumfrontsign/", "../../../OnsetModding/Plugins/pmediumfrontsign/Content")
	res = ReplaceObjectModelMesh(56, "/pmediumfrontsign/pmediumfrontsign")
	local pakname = "psign"
	local res = LoadPak(pakname, "/psign/", "../../../OnsetModding/Plugins/psign/Content")
	res = ReplaceObjectModelMesh(55, "/psign/policesign")
	local pakname = "psmallfrontsign"
	local res = LoadPak(pakname, "/psmallfrontsign/", "../../../OnsetModding/Plugins/psmallfrontsign/Content")
	res = ReplaceObjectModelMesh(54, "/psmallfrontsign/psmallfrontsign")
	local pakname = "pstaarrow"
	local res = LoadPak(pakname, "/pstaarrow/", "../../../OnsetModding/Plugins/pstaarrow/Content")
	res = ReplaceObjectModelMesh(53, "/pstaarrow/pstaarrow")
	local pakname = "keyboard"
	local res = LoadPak(pakname, "/keyboard/", "../../../OnsetModding/Plugins/keyboard/Content")
	res = ReplaceObjectModelMesh(43, "/keyboard/clavier")
  	local pakname = "mouse"
	local res = LoadPak(pakname, "/mouse/", "../../../OnsetModding/Plugins/mouse/Content")
	res = ReplaceObjectModelMesh(46, "/mouse/souris")
  	local pakname = "pvehonly"
	local res = LoadPak(pakname, "/pvehonly/", "../../../OnsetModding/Plugins/pvehonly/Content")
	res = ReplaceObjectModelMesh(52, "/pvehonly/pvehonly")
    local pakname = "luminousarrow"
	local res = LoadPak(pakname, "/luminousarrow/", "../../../OnsetModding/Plugins/luminousarrow/Content")
	res = ReplaceObjectModelMesh(44, "/luminousarrow/flechelumineuse")
	local pakname = "pcscreenfive"
	local res = LoadPak(pakname, "/pcscreenfive/", "../../../OnsetModding/Plugins/pcscreenfive/Content")
	res = ReplaceObjectModelMesh(58, "/pcscreenfive/ecranpcmec")
	local pakname = "pcscreentwo"
	local res = LoadPak(pakname, "/pcscreentwo/", "../../../OnsetModding/Plugins/pcscreentwo/Content")
	res = ReplaceObjectModelMesh(59, "/pcscreentwo/ecranpcpol")
	local pakname = "pcscreenthree"
	local res = LoadPak(pakname, "/pcscreenthree/", "../../../OnsetModding/Plugins/pcscreenthree/Content")
	res = ReplaceObjectModelMesh(60, "/pcscreenthree/ecranpcwri")
	local pakname = "pcscreensix"
	local res = LoadPak(pakname, "/pcscreensix/", "../../../OnsetModding/Plugins/pcscreensix/Content")
	res = ReplaceObjectModelMesh(51, "/pcscreensix/ecranpcbro")
	local pakname = "pcscreenone"
	local res = LoadPak(pakname, "/pcscreenone/", "../../../OnsetModding/Plugins/pcscreenone/Content")
	res = ReplaceObjectModelMesh(62, "/pcscreenone/ecranpc")
	local pakname = "pcscreenfour"
	local res = LoadPak(pakname, "/pcscreenfour/", "../../../OnsetModding/Plugins/pcscreenfour/Content")
	res = ReplaceObjectModelMesh(61, "/pcscreenfour/ecranpcems")
	local pakname = "adscreentwo"
	local res = LoadPak(pakname, "/adscreentwo/", "../../../OnsetModding/Plugins/adscreentwo/Content")
	res = ReplaceObjectModelMesh(178, "/adscreentwo/ecran2")
	local pakname = "ecranhumoriste"
	local res = LoadPak(pakname, "/ecranhumoriste/", "../../../OnsetModding/Plugins/ecranhumoriste/Content")
	res = ReplaceObjectModelMesh(179, "/ecranhumoriste/ecranhumoriste")
    local pakname = "panneauprefecture"
	local res = LoadPak(pakname, "/panneauprefecture/", "../../../OnsetModding/Plugins/panneauprefecture/Content")
	res = ReplaceObjectModelMesh(180, "/panneauprefecture/panneauprefecture")
  	local pakname = "phone"
	local res = LoadPak(pakname, "/phone/", "../../../OnsetModding/Plugins/phone/Content")
	res = ReplaceObjectModelMesh(181, "/phone/phone")
    local pakname = "sol"
	local res = LoadPak(pakname, "/sol/", "../../../OnsetModding/Plugins/sol/Content")
	res = ReplaceObjectModelMesh(182, "/sol/sol")
    local pakname = "solbois"
	local res = LoadPak(pakname, "/solbois/", "../../../OnsetModding/Plugins/solbois/Content")
	res = ReplaceObjectModelMesh(183, "/solbois/solbois")
     local pakname = "plafon"
	local res = LoadPak(pakname, "/plafon/", "../../../OnsetModding/Plugins/plafon/Content")
	res = ReplaceObjectModelMesh(184, "/plafon/plafon")
    local pakname = "carpet"
	local res = LoadPak(pakname, "/carpet/", "../../../OnsetModding/Plugins/carpet/Content")
	res = ReplaceObjectModelMesh(185, "/carpet/carpet")
    local pakname = "ascenseur"
	local res = LoadPak(pakname, "/ascenseur/", "../../../OnsetModding/Plugins/ascenseur/Content")
	res = ReplaceObjectModelMesh(186, "/ascenseur/ascenseur")
end
AddEvent("OnPackageStart", OnPackageStart)